kont6last/config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :products

  devise_for :users
  root 'home#index'

end

kont6last/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
      if user.admin?
        can :manage, :all
      else
        can :create, Product
        can :update, Product do |product|
          product.user ==  user
        end
        can :destroy, Product do |product|
          product.user ==  user
        end
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

kont6last/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  validates :name, presence: true,
                    length: { minimum: 3, maximum: 250 }
end

kont6last/app/models/product.rb
class Product < ActiveRecord::Base

  default_scope -> { order(created_at: :desc) }

  belongs_to :category
  belongs_to :user

  validates :name, presence: true, length: { minimum: 3, maximum: 255 }
  validates :category_id, presence: true
  validates :user_id, presence: true
  validates :content, presence: true, length: { minimum: 3 }
  validates :contacts, presence: true

end

kont6last/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: { minimum: 3, maximum: 250 }
end

kont6last/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |ex|
    redirect_to root_url, :alert => ex.message
  end

  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   end

end

kont6last/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy, :index]
  before_action :check_admin, only: [:new, :create, :edit, :destroy, :index]

  def index
      @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @products = Product.where(category_id: @category.id)
  end

  def edit
    authorize! :manage, :all
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.products.count == 0
      Category.find(params[:id]).destroy
      flash[:success] = "Категория удалена!"
      redirect_to categories_path
    else
      flash[:success] = "Эту категорию нельзя удалить"
      redirect_to categories_path
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:success] = "Категория отредактирована!"
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Категория создана!"
      redirect_to categories_path
    else
      render 'new'
    end
  end


      private

        def check_admin
          unless current_user.admin == true
            flash[:success] = "недостаточно прав"
            redirect_to root_path
          end
        end

        def category_params
          params.require(:category).permit(:name)
        end

end

kont6last/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
  end
end

kont6last/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy, :index]

  def index
    redirect_to root_path
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Объявление успешно размещено"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    authorize! :update, Product
    @product = Product.find(params[:id])
  end

  def edit
    authorize! :update, @product
    @product = Product.find(params[:id])
    # if current_user.id != @product.user_id
    #   flash[:success] = "Недостаточно прав"
    #   redirect_to root_path
    # end
  end

  def destroy
    @product = Product.find(params[:id])
    if current_user.id != @product.user_id
      flash[:success] = "Недостаточно прав"
      redirect_to root_path
    end
    Product.find(params[:id]).destroy
    flash[:success] = "Продукт успешно удален!"
    redirect_to root_path
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:success] = "Продукт отредактирован"
      redirect_to root_path
    else
      render 'edit'
    end
  end




        private

          def product_params
            params.require(:product).permit(:name, :user_id, :category_id, :contacts, :content)
          end
end

kont6last/app/helpers/application_helper.rb
module ApplicationHelper
  def all_categories
    Category.all
  end
end

kont6last/app/helpers/categories_helper.rb
module CategoriesHelper
end

kont6last/app/helpers/products_helper.rb
module ProductsHelper
end

kont6last/app/views/categories/_category.html.erb
<tr>
  <td><%= category.name %></td>
  <td><%= link_to "Редактировать", edit_category_path(category.id) %>
   |
  <%= link_to "Удалить", category, method: :delete,
                        data: { confirm: "Вы уверены?" } %></td>
</tr>

kont6last/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label "Название категории:" %>
  <%= f.text_field :name %>

  <%= f.submit "Сохранить", class: "btn btn-primary" %>
<% end %>

kont6last/app/views/categories/edit.html.erb
<h1>Редактирование категориии</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

  <%= render 'form' %>

  </div>
</div>

kont6last/app/views/categories/index.html.erb
<h1>Все категории</h1>

<p>
    <%= link_to 'Добавить категорию', new_category_path, class: 'btn btn-primary' %>
</p>

<table class = "table table-striped">
  <th>Название</th>
  <th>Действия</th>
  <%= render @categories %>
</table>

kont6last/app/views/categories/new.html.erb
<h1>Создание новой категории</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= render 'form' %>

  </div>
</div>

kont6last/app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<table class = "table table-striped">
  <th>Категория</th>
  <th>Объявление</th>
  <th>Автор</th>
  <% @products.each do |product| %>
  <tr>
    <td><%= link_to product.category.name, category_path(product.category.id) %></td>
    <td><%= link_to product.name, product_path(product.id) %></td>
    <td><%= product.user.name %></td>
  </tr>
  <% end %>

</table>

kont6last/app/views/home/index.html.erb
<table class = "table table-striped">
  <th>Категория</th>
  <th>Объявление</th>
  <th>Автор</th>
  <% @products.each do |product| %>
  <tr>
    <td><%= link_to product.category.name, category_path(product.category.id) %></td>
    <td><%= link_to product.name, product_path(product.id) %></td>
    <td><%= product.user.name %></td>
  </tr>
  <% end %>

</table>

kont6last/app/views/layouts/_show_category_list.html.erb
<% all_categories.each do |c| %>
     <div><%= link_to "#{c.name} (#{c.products.count})", category_path(c.id) %></div>
<% end %>

kont6last/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kont6last</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Барахолка</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if current_user %>

          <li><%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %></li>
          <li><%= link_to "Добавить объявление", new_product_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% if can? :manage, :all %>
            <li><%= link_to "Категории", categories_path %></li>
          <% end %>

            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>


            <% end %>
        </ul>
      </div>
    </div>
  </nav>


  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <div id="menu">
     <div><a href="/">Все категории</a></div>
     <div class="line"></div>
     <%= render 'layouts/show_category_list' %>
    </div>
    <div id="content">
<%= yield %>
    </div>
    <div id="foot">
    By NePo 2017. Жизнь - боль (с)
    </div>

<%= debug(params) if Rails.env.development? %>

</body>
</html>

kont6last/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label "Название продукта:" %>
  <%= f.text_field :name %>

  <%= f.label "Категория" %>
  <%= f.collection_select :category_id, Category.all, :id, :name %>

  <%= f.label "Текст объявления" %>
  <%= f.text_area :content %>

  <%= f.label "Контактные данные:" %>
  <%= f.text_field :contacts %>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <%= f.submit "Сохранить", class: "btn btn-primary" %>
<% end %>

kont6last/app/views/products/edit.html.erb
<h1>Редактирование товара</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

  <%= render 'form' %>

  </div>
</div>

kont6last/app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

kont6last/app/views/products/new.html.erb
<h1>Создание новой продукции</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= render 'form' %>

  </div>
</div>

kont6last/app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3>Категория: <%= link_to @product.category.name, category_path(@product.category.id) %>, by <%= @product.user.name %></h3>
<h3>Подробности:</h3>
<%= @product.content %>
<br>
<h3>Контакты</h3>
<%= @product.contacts %><hr>
<% if can? :update, @product %>
<%= link_to "Редактировать", edit_product_path(@product.id), class: "btn btn-primary" %>
<% end %>
<% if can? :destroy, @product %>
  <%= link_to "Удалить", @product, method: :delete, class: "btn btn-primary", data: { confirm: "Вы уверены?" } %>
<% end %>