config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users

  scope :photo do
    resources :comments, only: [:new, :create]
  end
  resources :users, only: [:index, :show]
  resources :photos

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)

      # can :destroy, Photo do |photo|
      #   photo.user == user
      # end
      can :destroy, Photo, user_id: user.id
      #
      # can :show_link, Photo do |photo|
      #   photo.user == user
      # end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  RAIT = (1..5).to_a
  validates :content, presence: true
  validates :star, presence: true, numericality: true

  validates_numericality_of :star, :greater_than_or_equal_to => 1
  validates_numericality_of :star, :less_than_or_equal_to => 5

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  belongs_to :user
  mount_uploader :pic, AvatarUploader

  # validates :pic, presence: true
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :username, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  include ApplicationHelper

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
        if @comment.save
          flash[:success] = "Комментарий добавлен"
          redirect_to "/photos/#{@comment.photo_id}"
        else
          flash[:error] = "Правильно заполните поля"
          redirect_to "/photos/#{@comment.photo_id}"
        end
  end

  def destroy
    @comment = Comment.destroy(params[:id])
    redirect_to "/photos/#{@comment.photo_id}"
  end


    private

    def comment_params
      params.require(:comment).permit(:content, :photo_id, :star)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @photos = Photo.paginate(:page => params[:page], :per_page => 3)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def new
    if user_signed_in?
      @photo = Photo.new
    else
      flash[:success] = "Только авторизированные пользователи могут создавать фотографии"
      redirect_to root_path
    end
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    if @photo.save
      flash[:success] = "Фото загружено"
      # redirect_to @category #redirect_to category_url(@category)
      #redirect_to categories_path
      redirect_to "/users/#{@photo.user_id}"
    else
      render 'new'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    if @photo.user_id == current_user.id
      @photo = Photo.find(params[:id]).destroy
      flash[:success] = "Фото удалено"
      redirect_to :back
    else
      flash[:success] = "Вы не можете удалить чужое фото"
      redirect_to :back
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

    private

      def photo_params
        params.require(:photo).permit(:name, :pic)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def find_avarege_score(id)
    @photo = Photo.find(id)
    count_row = @photo.comments.count
    if count_row == 0
      return "no votes"
    else
      sum_row = @photo.comments.sum(:star)*1.0
      stars = sum_row/count_row
      format("%.1f", stars)
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= will_paginate @photos %>
<hr>
<div class="container">
  <div class="box">
<% @photos.each do |photo| %>
  <h4>photo.name by <%= link_to photo.user.username, "/users/#{photo.user.id}" %></h4>
  <%=link_to( image_tag(photo.pic_url(:thumb)), "/photos/#{photo.id}") %>

<% end %>
  </div>
</div>
<hr>
<%= will_paginate @photos %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KR6</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">PHOTOWORLD</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <ul class="nav navbar-nav">
            <li><%= link_to "All users", users_path %></li>

            <% if user_signed_in? %>

              <li>
                <%= link_to("My profile - #{current_user.username}", "/users/#{current_user.id}")%>
              </li>
              <li>
                <%= link_to('Edit profile', edit_user_registration_path(current_user))%>
              </li>
              <li>
                <%= link_to('Add Photo', new_photo_path)%>
              </li>
              <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>

            <% else %>
              <li>
              <%= link_to('Login', new_user_session_path)  %>
              </li>
              <li>
                <%= link_to('Sign up', new_user_registration_path)  %>
              </li>
            <% end %>
          
          </ul>
        </ul>
      </div>
    </div>
  </nav>

  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/photos/new.html.erb
<h1>Добавление фото </h1>
<%= form_for(@photo) do |f| %>

<%= render 'shared/error_messages', object: f.object %>

<%= f.label "Название фото" %>
<%= f.text_field :name %>

<%= f.label "Обложка" %><br />
<%= f.file_field :pic %>

<%= f.submit "Сохранить"%>

<% end %>

app/views/photos/show.html.erb
<h2><%= @photo.name%></h2>
<%= image_tag @photo.pic_url(:normal_size) %>
<h3>Avarage score: <%= find_avarege_score(@photo.id)%></h3>
<% if user_signed_in? %>
<h2>Add Comment</h2>
<div class="row">
  <div class="span6 offset3">
      <%= form_for(:comment, url: comments_path) do |f| %>

        <%= f.label :star %>
        <%= f.collection_select :star, Comment::RAIT, :to_i, :to_i %>

        <%= f.label :content %>
        <%= f.text_area :content %>

        <%= f.hidden_field :photo_id, :value => @photo.id %>

        <%= f.submit "Добавить комментарий", class: "btn btn-large btn-primary" %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

<h2>Lists of Comments</h2>
<% @photo.comments.each do |comment| %>
<li>
    <strong>By <%= comment.user.username %>, score: <%= comment.star %></strong><br>
    <%= comment.content %>
</li>

<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>List of Users</h1>

<ul>
<% @users.each do |user| %>
  <li><%= link_to(user.username, user_path(user.id)) %></li>
<% end %>
</ul>

app/views/users/show.html.erb
<b><%= @user.username %></b>


<table class="table table-striped">

<th>Image</th>
<th>Title</th>
<th>Actions</th>

<% @user.photos.each do |photo| %>
  <tr>
    <td><%= link_to( image_tag(photo.pic_url(:thumb)), "/photos/#{photo.id}") %></td>
    <td><%= photo.name %></td>
    <td><%= link_to "Delete", photo, method: :delete, class: 'btn btn-primary', data: { confirm: "Are you sure?"} if can? :destroy, photo %> - <%= link_to "Show photo", "/photos/#{photo.id}" %> </td>
  </tr>
<% end %>

</table>